package com.meshchats.app.crypto

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import java.security.KeyStoreException
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Classifies an exception thrown while unwrapping a Keystore-wrapped secret into
 * a bounded [SecretUnwrapError]. Extracted from [AndroidKeystoreSecretWrapper] so
 * it can be unit-tested on the host JVM, where a device credential reset (and the
 * `KeyPermanentlyInvalidatedException` it raises) cannot be reproduced.
 *
 * Classification walks the cause chain (some providers wrap the real cause), and
 * matches by class name — `android.security.keystore.KeyPermanentlyInvalidatedException`
 * is not on the host classpath as a real class, so a name match keeps this both
 * device-correct and JVM-testable:
 * - a `KeyPermanentlyInvalidatedException` anywhere in the chain means the
 *   wrapping key is gone for good → [SecretUnwrapError.KEY_LOST];
 * - an [AEADBadTagException] anywhere in the chain means authentication failed →
 *   [SecretUnwrapError.TAMPERED];
 * - anything else is an operational failure → [SecretUnwrapError.UNWRAP_FAILED].
 *
 * Key loss is checked first: an invalidated key is a permanent, unrecoverable
 * state that must never be misreported as mere tampering or a transient fault.
 */
internal fun classifyKeystoreUnwrapError(error: Throwable?): SecretUnwrapError {
    var cur = error
    var depth = 0
    var sawBadTag = false
    while (cur != null && depth < 16) {
        if (cur.javaClass.name.endsWith("KeyPermanentlyInvalidatedException")) {
            return SecretUnwrapError.KEY_LOST
        }
        if (cur is AEADBadTagException) sawBadTag = true
        cur = cur.cause
        depth++
    }
    return if (sawBadTag) SecretUnwrapError.TAMPERED else SecretUnwrapError.UNWRAP_FAILED
}

/**
 * [SecretWrapper] backed by a non-exportable AES-256-GCM key in the Android
 * Keystore. The key material never leaves the Keystore (TEE/StrongBox where
 * available); this class only ever holds a [SecretKey] handle, never raw key
 * bytes, so the wrapping key cannot be exfiltrated even if app memory is dumped.
 *
 * Each key alias is independent, giving callers domain separation at the key
 * level (e.g. a distinct alias for the database key vs. the identity key). AEAD
 * associated data provides a second, in-record domain-separation layer so a blob
 * wrapped for one logical purpose fails authentication if replayed under another.
 *
 * GCM nonces are generated by the platform provider (`Cipher.getIV()` after init)
 * rather than supplied by the caller, which is the Android-recommended pattern:
 * AndroidKeyStore refuses caller-supplied IVs for GCM to prevent nonce reuse
 * under the same key.
 *
 * All failures collapse to bounded [WrapResult.Failure] / [UnwrapResult.Failure]
 * values; no Keystore exception type leaks to callers, and no plaintext or key
 * material is ever logged.
 */
class AndroidKeystoreSecretWrapper(
    private val alias: String,
    private val keyStoreProvider: String = ANDROID_KEY_STORE,
) : SecretWrapper, KeyMaterialDestroyer {

    companion object {
        private const val ANDROID_KEY_STORE = "AndroidKeyStore"
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
        private const val GCM_TAG_BITS = 128
        private const val KEY_SIZE_BITS = 256
    }

    override fun wrap(plaintext: ByteArray, associatedData: ByteArray): WrapResult {
        val key = try {
            getOrCreateKey()
        } catch (_: Exception) {
            return WrapResult.Failure(SecretWrapError.KEY_UNAVAILABLE)
        }

        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, key)
            cipher.updateAAD(associatedData)
            val ciphertext = cipher.doFinal(plaintext)
            // The provider chose the nonce; capture it for storage.
            val nonce = cipher.iv
            WrapResult.Success(WrappedSecret(nonce = nonce, ciphertext = ciphertext))
        } catch (_: Exception) {
            WrapResult.Failure(SecretWrapError.WRAP_FAILED)
        }
    }

    override fun unwrap(nonce: ByteArray, ciphertext: ByteArray, associatedData: ByteArray): UnwrapResult {
        val key = try {
            existingKey()
        } catch (_: Exception) {
            return UnwrapResult.Failure(SecretUnwrapError.UNWRAP_FAILED)
        } ?: return UnwrapResult.Failure(SecretUnwrapError.KEY_LOST)

        return try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_BITS, nonce))
            cipher.updateAAD(associatedData)
            val plaintext = cipher.doFinal(ciphertext)
            UnwrapResult.Success(plaintext)
        } catch (e: Exception) {
            // A permanently invalidated key (credential reset) surfaces here rather
            // than as a null lookup, and must be reported as KEY_LOST. Tamper (bad
            // AEAD tag) and operational failures are classified from the same chain.
            UnwrapResult.Failure(classifyKeystoreUnwrapError(e))
        }
    }

    /**
     * Destroys this wrapper's Keystore alias, making every secret ever wrapped
     * under it cryptographically unrecoverable — even if the wrapped blob still
     * exists on disk, there is no longer any key to unwrap it with.
     *
     * Idempotent and fail-closed: an already-absent alias is [WrappingKeyDeleteResult.Deleted];
     * a delete that cannot be confirmed absent afterward is [WrappingKeyDeleteResult.Failure].
     * The alias is re-checked after deletion so success is only reported when the
     * key is genuinely gone. Never throws and never recreates the key.
     */
    override fun destroy(): WrappingKeyDeleteResult {
        val ks = try {
            loadKeyStore()
        } catch (_: Exception) {
            return WrappingKeyDeleteResult.Failure(WrappingKeyDeleteError.STORE_UNAVAILABLE)
        }

        val present = try {
            ks.containsAlias(alias)
        } catch (_: Exception) {
            // Cannot even determine presence: treat the store as unavailable rather
            // than claim the key is gone.
            return WrappingKeyDeleteResult.Failure(WrappingKeyDeleteError.STORE_UNAVAILABLE)
        }
        // Already absent: the domain is destroyed. Converges on a repeated wipe.
        if (!present) return WrappingKeyDeleteResult.Deleted

        try {
            ks.deleteEntry(alias)
        } catch (_: Exception) {
            return WrappingKeyDeleteResult.Failure(WrappingKeyDeleteError.DELETE_FAILED)
        }

        // Confirm absence: only report success if the alias is genuinely gone, so a
        // coordinator never over-claims a completed wipe on a silent no-op delete.
        val stillThere = try {
            ks.containsAlias(alias)
        } catch (_: Exception) {
            // Post-delete check failed: be conservative and report failure.
            return WrappingKeyDeleteResult.Failure(WrappingKeyDeleteError.DELETE_FAILED)
        }
        return if (stillThere) {
            WrappingKeyDeleteResult.Failure(WrappingKeyDeleteError.DELETE_FAILED)
        } else {
            WrappingKeyDeleteResult.Deleted
        }
    }

    private fun loadKeyStore(): KeyStore =
        KeyStore.getInstance(keyStoreProvider).apply { load(null) }

    private fun existingKey(): SecretKey? {
        val ks = loadKeyStore()
        val entry = try {
            ks.getEntry(alias, null)
        } catch (_: KeyStoreException) {
            null
        }
        return (entry as? KeyStore.SecretKeyEntry)?.secretKey
            ?: (ks.getKey(alias, null) as? SecretKey)
    }

    private fun getOrCreateKey(): SecretKey {
        existingKey()?.let { return it }

        val generator = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, keyStoreProvider)
        val spec = KeyGenParameterSpec.Builder(
            alias,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
        )
            .setKeySize(KEY_SIZE_BITS)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            // Caller-supplied IVs are refused for GCM; the provider generates a
            // fresh random nonce per encryption, preventing nonce reuse.
            .setRandomizedEncryptionRequired(true)
            .build()
        generator.init(spec)
        return generator.generateKey()
    }
}
