package com.meshchats.app.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Replay state for PQXDH Kyber prekey consumption. libsignal's official
 * `InMemoryKyberPreKeyStore` records, per Kyber prekey, the set of initiator base
 * keys it has already accepted so a second PREKEY message reusing the same base
 * key against the same Kyber+signed-prekey pair is rejected as a replay
 * (`ReusedBaseKeyException`) rather than silently re-deriving the same shared
 * secret.
 *
 * Each row is the exact triple `(kyber_prekey_id, signed_prekey_id, base_key)`
 * where [baseKey] is the byte-for-byte serialized libsignal `ECPublicKey` of the
 * initiator's base key. Uniqueness is enforced at the database level over the
 * exact triple (a surrogate autogenerated primary key plus a unique index on all
 * three columns), not over any hash of the base key — so detection is exact and
 * collision-free, and a concurrent duplicate is caught by the constraint rather
 * than a check-then-insert race.
 *
 * The Kyber id carries a foreign key to `signal_kyber_prekeys` with cascade
 * delete: replay records never outlive the Kyber prekey they protect.
 */
@Entity(
    tableName = "signal_kyber_base_keys",
    foreignKeys = [
        ForeignKey(
            entity = SignalKyberPreKeyEntity::class,
            parentColumns = ["kyber_prekey_id"],
            childColumns = ["kyber_prekey_id"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [
        // Exact-triple uniqueness at the DB level. Concurrency-safe: a duplicate
        // insert violates this constraint instead of relying on a prior read.
        Index(
            value = ["kyber_prekey_id", "signed_prekey_id", "base_key"],
            unique = true,
            name = "index_signal_kyber_base_keys_triple",
        ),
        // Supports cascade delete lookups and audit queries by Kyber id.
        Index(value = ["kyber_prekey_id"]),
    ],
)
data class SignalKyberBaseKeyEntity(
    /** Surrogate row id; the semantic key is the unique triple below. */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,

    @ColumnInfo(name = "kyber_prekey_id") val kyberPreKeyId: Int,

    @ColumnInfo(name = "signed_prekey_id") val signedPreKeyId: Int,

    /** Byte-for-byte serialized libsignal ECPublicKey base key. */
    @ColumnInfo(name = "base_key", typeAffinity = ColumnInfo.BLOB)
    val baseKey: ByteArray,

    @ColumnInfo(name = "first_seen_at") val firstSeenAt: Long,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is SignalKyberBaseKeyEntity) return false
        return id == other.id &&
            kyberPreKeyId == other.kyberPreKeyId &&
            signedPreKeyId == other.signedPreKeyId &&
            baseKey.contentEquals(other.baseKey) &&
            firstSeenAt == other.firstSeenAt
    }

    override fun hashCode(): Int {
        var result = id.hashCode()
        result = 31 * result + kyberPreKeyId
        result = 31 * result + signedPreKeyId
        result = 31 * result + baseKey.contentHashCode()
        result = 31 * result + firstSeenAt.hashCode()
        return result
    }
}

/**
 * Bounded, typed outcome of [SignalKyberBaseKeyDao.markKyberUsedWithBaseKey]. The
 * transaction never leaks a raw SQL exception for the expected replay/absent
 * cases; it returns one of these instead. Task 2's libsignal adapter maps
 * [REUSED] to `ReusedBaseKeyException`, keeping this DAO free of any libsignal
 * dependency.
 */
enum class MarkKyberUsedResult {
    /**
     * First time this exact triple was seen: the replay row was inserted and the
     * Kyber prekey was marked used. Fresh consumption.
     */
    MARKED,

    /**
     * The exact `(kyber_prekey_id, signed_prekey_id, base_key)` triple already
     * existed: a replay. Nothing was written and no state changed; the caller
     * (Task 2) surfaces this as `ReusedBaseKeyException`.
     */
    REUSED,

    /**
     * No Kyber prekey with the given id exists. Nothing was written; the caller
     * surfaces this as the libsignal "no such Kyber prekey" failure.
     */
    MISSING,
}
